### PR TITLE
Attempting to fix issues with Rails' autoloader

### PR DESCRIPTION
**Pull request by pnomolos**
Use `to_s` on the klass so we check equality based on the class name, not the class itself.  Also de-register the types every time the autoloader is run, so we explicitly don't reload a class if it's already registered.

### CODE REVIEW

**Comment by pnomolos** [comment]
I'm not sure if anyone else is using this gem or just me, if anyone else _is_ using this could they please check and see if this causes issues for them? :)

**Comment by jeromegn** [comment]
Ah, have you tried monkey patching the gem in your rails app to see if it works?

**Comment by pnomolos** [comment]
@jeromegn Yes, and it's working fine for me.  It'd just been nice to get confirmation from anyone else that this approach I'm using doesn't cause anyone else issues :)

**Comment by jeromegn** [comment]
Is this still a good fix? :)

**Comment by pnomolos** [comment]
My team hasn't reported any regressions, so for us at least it's working :)

**Pull request merged**
